minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minio123
  region: sa-east-1
  bucket: docs

spring:
  application:
    name: minio-demo

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB